### ISSUE TITLE
No releases

### ISSUE THREAD

**Issue by realdep** [Obscurely/DiscordNitroSniper#1]
Releases tab empty
me lazy, me no have visual studio, me can not compile
please post binaries

thanks you

**Comment by realdep** [comment]
ok my dumbass didnt read the compiling section, please delete this issue

**Comment by Obscurely** [comment]
Sorry for not providing binaries, but I was really busy in the last couple of months and also didn't expected anyone to come across this since I never promoted it anywhere. I'm gonna compile some binaries right now.
